spring:
    application:
        name: cards
    datasource:
        url: jdbc:h2:mem:cardb
        driver-class-name: org.h2.Driver
        username: sa
        password: sa
    flyway:
        baseline-on-migrate: true
        url: jdbc:h2:mem:cardb
        user: sa
        password: sa
    h2:
        console:
            enabled: true
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
        show-sql: true
server:
    port: 8082
